# This should be placed in this file /opt/tomcat/webapps/bookbattery/properties
#########################################################################
#                            bookbattery                                #
#########################################################################

#-------------------- JSP Paths Starts here --------------------#

JspUrl = /bookbattery/
#-------------------- DATABASE SERVER-0 --------------------#
DATABASESERVERNAME           = mysql

DATABASEDRIVER               = org.gjt.mm.mysql.Driver

DATABASEURL                  = jdbc:mysql://localhost/bookbatterydb?useOldAliasMetadataBehavior=true & autoReconnect=true

DATABASEUSERNAME             = bookbattery
DATABASEPASSWORD             =

DataBaseInitialConnections   = 5
DataBaseMaxConnections       = 20
DataBaseWaitIfBusy           = true



#---------surfmug---------------------------#
publicUrl = http://www.bookbattery.com
#publicUrl = http://stage1.bookbattery.com
#publicUrl = http://52.90.194.106
#publicUrl = http://localhost
#---------domainname------------------------#
domainname = bookbattery.com
#domainname = stage1.bookbattery.com
#domainname = 52.90.194.106
#domainname = localhost

#---------PostsPagecount------------------------#
updatesPerPage = 20;


#----------------------------- log file values -----------------------------#
LogLevel              = 5
LogFilePath     = /home/ngit/tomcat/webapps/bookbattery/logs/
LogFileName      = bookbattery.log

#FileUploadLocalPath = C:/Program Files/Apache Software Foundation/Tomcat 5.0/webapps/bookbattery/temp/
FileUploadLocalPath = ../temp/

# Excel sheet path absolute/relative
#ExcelSheetFilePath = C:/Program Files/Apache Software Foundation/Tomcat 5.0/webapps/bookbattery/temp/
ExcelSheetFilePath = ../temp/

PDFFilePath = .userdata/billing/consumerinvoices
PDFRelFilePath = userdata/billing/consumerinvoices
PDFFilePath1 = userdata/billing/salesorders
RelativePathLaptopBatteries=userdata/batterystore/laptopbatteries
ExcelRelFilePath = temp/

# Number of videos/images allowed with each post
UPDATES_ATTACHMENT_LIMIT=4
# company percentage to generate retailer invoice
company_commision = 0.1127
servicetax = 114.5

# Virtual File Path
VirtualPath=/home/ngit/tomcat/webapps

# Relative File Path
RelativePath=userdata/posts
RelativePathbat=userdata/batterystore
THUMBNAIL_SCRIPT_PATH=properties/thumbnail.pl
# IP address of the content server to form url
CMS_SERVER_IP=www.bookbattery.com
#CMS_SERVER_IP=stage1.bookbattery.com
#CMS_SERVER_IP=52.90.194.106
#CMS_SERVER_IP=localhost

#----------- support mobile number -----#
suppmobnumber = 9603467559

suppemaild = helpdesk.bookbattery@gmail.com

#-------EmailId ----------------#
SupportEmailId = BookBattery<helpdesk.bookbattery@gmail.com>


 #----------- Ads disabled/enabled -----#
ADVERTISEMENTS=YES
#-------From address for SMS----------------#
SMSFromAddress=ASSIST
#-------Base url----------------#
baseURL = http://www.bookbattery.com
#baseURL = http://stage1.bookbattery.com
#baseURL = http://52.90.194.106
#baseURL = http://localhost

#----------- Base Url Directory-----#
baseurldirectory=/bookbattery/

#----------- Chat Agent Profile Image uploads configurations -----#

RelativePath4=userdata/

#----------- Script to create thumbnail images for chat agent in admin-----------#

THUMBNAIL_SCRIPT_PATH3=properties/thumbnails.pl
RelativePathloy=userdata/loyalty
THUMBNAIL_SCRIPT_PATH2=properties/thumbnail2.pl

#----------- Live Chat Admin Login Details -----#

loginname=admin
password=TPK03

#----------- product logo and welcome message configurations -----#

productlogo=images/noimage.jpg
welcomemsg=Welcome to BookBattery

#----------- SurfMug logo and welcome message configurations -----#

batterywalelogo=images/bookbatterylogo.png
welcomemsgbatterywale=Welcome to BookBattery Live

#----------- support name message in email -----#

supportname=BookBattery Live Chat

#---------- logo to display in admin livechat management and chat agent login ----------#

adminlogo=images/bookbatterylogo.png

#------- EmailId from this one mails will sent to users ----------------#

#SupportEmailId = SurfMug<info@meraopinion.com>

#------- Live chat admin email id---------------#

livechatadminemail = helpdesk.bookbattery@gmail.com

#------ Live chat properties ends here ----------#

#----------- Consumer Loyality points details -----#
NewInvitations=5
AddNewRetailer=10
Onlinesurvey=10
Reportingnews=5
Redeem_points=100
Loyalitypoints_count=5
Recharge_loyalty_money=2
Redeem_expiry_days=30

#----------- Book Battery Service-----#
Bookbatteryservice=Yes

#-------Navigate to Another Server url----------------#
serverURL = www.bookbattery.com
#serverURL = stage1.bookbattery.com
#serverURL = 52.90.194.106
#serverURL = localhost

#-------Operator Team Count----------------#
OperatorTeamCount = 2

server.tomcat.uri-encoding=utf-8
