alter table location_area add column state varchar(30);
update location_area set state='Uttar Pradesh' where location = 'Agra';
update location_area set state='Gujarat' where location = 'Ahmedabad';
update location_area set state='Uttar Pradesh' where location = 'Aligarh';
update location_area set state='Uttar Pradesh' where location = 'Allahabad';
update location_area set state='Gujarat' where location = 'Anand';
update location_area set state='Andhra Pradesh' where location = 'Anantapur';
update location_area set state='Maharashtra' where location = 'Aurangabad';
update location_area set state='Uttar Pradesh' where location = 'Banda';
update location_area set state='Karnataka' where location = 'Bangalore';
update location_area set state='West Bengal' where location = 'Bardhaman';
update location_area set state='Uttar Pradesh' where location = 'Bareilly';
update location_area set state='Gujarat' where location = 'Baroda';
update location_area set state='Assam' where location = 'Barpeta';
update location_area set state='Uttar Pradesh' where location = 'Basti';
update location_area set state='Karnataka' where location = 'Belgaum';
update location_area set state='Gujarat' where location = 'Bharuch';
update location_area set state='Gujarat' where location = 'Bhavnagar';
update location_area set state='Madhya Pradesh' where location = 'Bhopal';
update location_area set state='Orissa' where location = 'Bhubaneswar';
update location_area set state='Assam' where location = 'Bongaigaon';
update location_area set state='Union Territories' where location = 'Chandigarh';
update location_area set state='Tamil Nadu' where location = 'Chennai';
update location_area set state='Andhra Pradesh' where location = 'Chittoor';
update location_area set state='Tamil Nadu' where location = 'Coimbatore';
update location_area set state='Andhra Pradesh' where location = 'Cuddapah';
update location_area set state='Orissa' where location = 'Cuttack';
update location_area set state='Gujarat' where location = 'Deesa';
update location_area set state='Assam' where location = 'Dhubri';
update location_area set state='Assam' where location = 'Dibrugarh';
update location_area set state='West Bengal' where location = 'East Midnapore';
update location_area set state='Andhra Pradesh' where location = 'Eluru';
update location_area set state='Uttar Pradesh' where location = 'Faizabad';
update location_area set state='Haryana' where location = 'Faridabad';
update location_area set state='Uttar Pradesh' where location = 'Farrukhabad';
update location_area set state='Uttar Pradesh' where location = 'Ghaziabad';
update location_area set state='Uttar Pradesh' where location = 'Gorakhpur';
update location_area set state='Andhra Pradesh' where location = 'Guntur';
update location_area set state='Haryana' where location = 'Gurgaon';
update location_area set state='Assam' where location = 'Guwahati';
update location_area set state='Uttar Pradesh' where location = 'Hardoi';
update location_area set state='Haryana' where location = 'Hissar';
update location_area set state='Tamil Nadu' where location = 'Hosur';
update location_area set state='Andhra Pradesh' where location = 'Hyderabad';
update location_area set state='Gujarat' where location = 'Idar';
update location_area set state='Madhya Pradesh' where location = 'Indore';
update location_area set state='Rajasthan' where location = 'Jaipur';
update location_area set state='Gujarat' where location = 'Jamnagar';
update location_area set state='Jharkhand ' where location = 'Jamshedpur';
update location_area set state='Uttar Pradesh' where location = 'Jhansi';
update location_area set state='Rajasthan' where location = 'Jodhpur';
update location_area set state='Assam' where location = 'Jorhat';
update location_area set state='Gujarat' where location = 'Junagadh';
update location_area set state='Haryana' where location = 'Kaithal';
update location_area set state='Andhra Pradesh' where location = 'Kakinada';
update location_area set state='Andhra Pradesh' where location = 'Karimnagar';
update location_area set state='Andhra Pradesh' where location = 'Khammam';
update location_area set state='West Bengal' where location = 'Kharagpur';
update location_area set state='Kerala' where location = 'Kochi';
update location_area set state='West Bengal' where location = 'Kolkata';
update location_area set state='Andhra Pradesh' where location = 'Kurnool';
update location_area set state='Gujarat' where location = 'Kutch';
update location_area set state='Uttar Pradesh' where location = 'Lakhimpur';
update location_area set state='Uttar Pradesh' where location = 'Lucknow';
update location_area set state='Andhra Pradesh' where location = 'Mahabubnagar';
update location_area set state='West Bengal' where location = 'Malda';
update location_area set state='Karnataka' where location = 'Mangalore';
update location_area set state='Uttar Pradesh' where location = 'Mathura';
update location_area set state='Uttar Pradesh' where location = 'Meerut';
update location_area set state='Gujarat' where location = 'Mehsana';
update location_area set state='Uttar Pradesh' where location = 'Moradabad';
update location_area set state='Maharashtra' where location = 'Mumbai';
update location_area set state='West Bengal' where location = 'Murshidabad';
update location_area set state='Uttar Pradesh' where location = 'Muzaffarnagar';
update location_area set state='Maharashtra' where location = 'Nagpur';
update location_area set state='Andhra Pradesh' where location = 'Nalgonda';
update location_area set state='Andhra Pradesh' where location = 'Nellore';
update location_area set state='Delhi' where location = 'New Delhi';
update location_area set state='Andhra Pradesh' where location = 'Nizamabad';
update location_area set state='Uttar Pradesh' where location = 'Noida';
update location_area set state='Andhra Pradesh' where location = 'Ongole';
update location_area set state='Haryana' where location = 'Panipat';
update location_area set state='Bihar' where location = 'Patna';
update location_area set state='Union Territories' where location = 'Pondicherry';
update location_area set state='Maharashtra' where location = 'Pune';
update location_area set state='West Bengal' where location = 'Purulia';
update location_area set state='Karnataka' where location = 'Raichur';
update location_area set state='Andhra Pradesh' where location = 'Rajahmundry';
update location_area set state='Gujarat' where location = 'Rajkot';
update location_area set state='Uttar Pradesh' where location = 'Saharanpur';
update location_area set state='Tamil Nadu' where location = 'Salem';
update location_area set state='Assam' where location = 'Sibsagar';
update location_area set state='Assam' where location = 'Silchar';
update location_area set state='West Bengal' where location = 'Siliguri';
update location_area set state='Andhra Pradesh' where location = 'Srikakulam';
update location_area set state='Gujarat' where location = 'Surendranagar';
update location_area set state='Assam' where location = 'Tezpur';
update location_area set state='Tamil Nadu' where location = 'Thanjavur';
update location_area set state='Tamil Nadu' where location = 'Thiruvallur';
update location_area set state='Tamil Nadu' where location = 'Tirunelveli';
update location_area set state='Andhra Pradesh' where location = 'Tirupati';
update location_area set state='Tamil Nadu' where location = 'Tiruppur';
update location_area set state='Tamil Nadu' where location = 'Trichy';
update location_area set state='Kerala' where location = 'Trivandrum';
update location_area set state='Tamil Nadu' where location = 'Tuticorin';
update location_area set state='Rajasthan' where location = 'Udaipur';
update location_area set state='Karnataka' where location = 'Udupi';
update location_area set state='Madhya Pradesh' where location = 'Ujjain';
update location_area set state='Gujarat' where location = 'Vapi';
update location_area set state='Tamil Nadu' where location = 'Vellore';
update location_area set state='Andhra Pradesh' where location = 'Vijayawada';
update location_area set state='Andhra Pradesh' where location = 'Visakhapatnam';
update location_area set state='Andhra Pradesh' where location = 'Warangal';
update location_area set state='Haryana' where location = 'Yamuna Nagar';