update inverter_details set inverter_name="Pure Sine Wave" where inverter_name="Home UPS";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="ILT 1224";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="ILT 14000XL";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="RC 15000";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="TST 1618";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="ILTT 18000";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="RC 18000";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="LET 19036";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="TST 1818";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="IL 18039";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="ILTT 18048";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="LT 500";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="ILTT 24048";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="RC 25000";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="ILTT 26048";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="LT 300";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="EC 18036";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="PC 18000";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="ILTJ 18030";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIP0-IP2000";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIP0-IP1800";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIP0-IP1500";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIP0-IP1350";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIP0-IP1000";
update application_chat_mapping set battery_type_flag="Flat Plate Battery" where bat_model="FIBO-IB1500";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="Exide Inva Red 500 Plus";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="Invamore1500";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="Invamore1800";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="FIM0-MI1500";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="FIM0-MI1000";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="EL Master 150";
update application_chat_mapping set battery_type_flag="Tall Tubular Battery" where bat_model="IM10000";
update application_chat_mapping set battery_type_flag="Tall Tubular" where bat_model="TM500";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="Exide Inva Red 450 Plus";
update application_chat_mapping set battery_type_flag="Tubular Battery" where bat_model="AAM-CR-TD100ST30";