CREATE TABLE laptop_battery_order_details(
`lap_bat_ord_id` int (10) NOT NULL auto_increment,
`consumer_name` varchar(50) NOT NULL,
`consumer_mobnumber` varchar(20) NOT NULL,
`consumer_emailid` varchar(50) NOT NULL,
`consumer_verif_code` int(10) NOT NULL,
`battery_type` varchar(25) NOT NULL,
`battery_brand` varchar(50) NOT NULL,
`battery_model` varchar(50) NOT NULL,
`laptop_make` varchar(30) NOT NULL,
`laptop_product` varchar(50) NOT NULL,
`laptop_model` varchar(50) NOT NULL,
`state` varchar (30) NOT NULL,
`city` varchar (30) NOT NULL,
`area` varchar(50) NOT NULL,
`price` varchar (25) NOT NULL,
`creation_date` datetime default '0000-00-00 00:00:00',
`created_by` varchar(20) default '',
`updated_date` datetime default '0000-00-00 00:00:00',
`updated_by` varchar(20) default '',
 PRIMARY KEY (`lap_bat_ord_id`));