DROP TABLE IF EXISTS `Telangana_retailers`;
CREATE TABLE  `Telangana_retailers` (
  `retailer_id` int(10) NOT NULL,
  `retailer_name` varchar(100) NOT NULL,
  `vendor_id` int(10) default NULL,
  `area` varchar(50) NOT NULL,
  `address1` text,
  `address2` text,
  `city` varchar(30) NOT NULL default '0',
  `state` varchar(30) default NULL,
  `zipcode` varchar(10) default NULL,
  `creation_date` datetime default NULL,
  `created_by` varchar(20) NOT NULL,
  `updated_date` datetime default NULL,
  `updated_by` varchar(20) default NULL,
  `password` varchar(50) NOT NULL,
  `retailer_loginname` varchar(50) default NULL,
  `phone_number` varchar(20) default NULL,
  `mobile_number` varchar(15) NOT NULL,
  `vendor_name` varchar(50) default NULL,
  `eretailer_flag` tinyint(1) NOT NULL,
  `email_id` varchar(100) default NULL,
  `certification_id` int(10) default '0',
  `certification_name` varchar(50) default 'Ordinary',
  `merchant_category` varchar(50) default 'Free',
  `merchant_certification` varchar(50) default 'Ordinary',
  `retailer_flag` varchar(10) default 'no',
  `paid_flag` varchar(5) default 'No',
  `mobile_numberother` varchar(55) default NULL,
  `phone_numberother` varchar(55) default NULL,
  `email_id1` varchar(150) NOT NULL,
  `merchantcategory_date` datetime default '3000-00-00 00:00:00',
  `status` varchar(10) NOT NULL default 'active',
  `account_expiry` datetime default '0000-00-00 00:00:00',
  `miniurl_flag` varchar(10) default 'No',
  `work_flag` varchar(10) default 'YES',
  `tollfree_number` varchar(20) default NULL,
  `miniurl_link` varchar(100) default 'NULL',
  `timings` varchar(100) default 'NA',
  `invoice_flag` varchar(10) default 'no',
  `modify_date` datetime default NULL,
  KEY `retailer_id` (`retailer_id`),
  KEY `retailer_name` (`retailer_name`),
  KEY `vendor_id` (`vendor_id`),
  KEY `area` (`area`),
  KEY `city` (`city`),
  KEY `retailer_loginname` (`retailer_loginname`),
  KEY `eretailer_flag` (`eretailer_flag`));