CREATE TABLE  `online_transaction_details` (
  `slno_id` int(10) NOT NULL auto_increment,
  `order_id` varchar(50) NOT NULL,
  `transaction_id` varchar(50) NOT NULL,
  `payment_request_id` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL default 'pending',
  `currency` varchar(50) NOT NULL default 'INR',
  `amount` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `description` text,
  `redirect_url` varchar(150) NOT NULL,
  `webhook_url` varchar(150) NOT NULL,
  `created_at` varchar(100),
  `resource_uri` varchar(300) NOT NULL,
  `payment_url` varchar(300) NOT NULL,
  `created_date` datetime default NULL,
  `updated_date` datetime default NULL,
  `fees` varchar(50) NOT NULL,
  `mac` varchar(100) default NULL,
  `payment_id` varchar(50) NOT NULL,
  PRIMARY KEY (`slno_id`)
  );
