update vehicle_details set  battery_type="Car Batteries" where battery_type="Four Wheelers";
update vehicle_details set  battery_type="Bike Batteries" where battery_type="Two Wheelers";
update vehicle_details set  battery_type="Three Wheeler Batteries" where battery_type="Three Wheelers";
update vehicle_details set  battery_type="Bus Batteries" where battery_type="Bus";
update vehicle_details set  battery_type="Truck Batteries" where battery_type="Trucks";
update vehicle_details set  battery_type="Tractor Batteries" where battery_type="Tractors";
update vehicle_details set  battery_type="Crane Batteries" where battery_type="Cranes";
update vehicle_details set  battery_type="Roller Batteries" where battery_type="Rollers";
update vehicle_details set  battery_type="Dozer Batteries" where battery_type="Dozers";
update vehicle_details set  battery_type="Excavator Batteries" where battery_type="Excavators";
update vehicle_details set  battery_type="Harvestor Batteries" where battery_type="Harvestor";
update vehicle_details set  battery_type="Compactor Batteries" where battery_type="Compactors";
update vehicle_details set  battery_type="Dumper Batteries" where battery_type="Dumpers";
update vehicle_details set  battery_type="Minibus Batteries" where battery_type="Minibus";
update vehicle_details set  battery_type="Tyre Handler Batteries" where battery_type="Tyre Handlers";
update vehicle_details set  battery_type="Wheeled Harvester Batteries" where battery_type="Wheeled harvester";
update vehicle_details set  battery_type="Forwarder Batteries" where battery_type="Forwarders";
update vehicle_details set  battery_type="Hydraulic Shovel Batteries" where battery_type="Hydraulic Shovel";
update vehicle_details set  battery_type="Construction Equipment Batteries" where battery_type="Construction Equipment";
update vehicle_details set  battery_type="Hydralic Excavator Batteries" where battery_type="Hydralic Excavators";
update vehicle_details set  battery_type="Loader Batteries" where battery_type="Loaders";
update vehicle_details set  battery_type="Telescopic Handler Batteries" where battery_type="Telescopic Handlers";
update vehicle_details set  battery_type="Generator Batteries" where battery_type="Generators";
update vehicle_details set  battery_type="Genset Batteries" where battery_type="Gensets";
update vehicle_details set  battery_type="Special Vehicle Batteries" where battery_type="Special Vehicles";



update application_chat_mapping set  bat_type="Car Batteries" where bat_type="Four Wheelers";
update application_chat_mapping set  bat_type="Bike Batteries" where bat_type="Two Wheelers";
update application_chat_mapping set  bat_type="Three Wheeler Batteries" where bat_type="Three Wheelers";
update application_chat_mapping set  bat_type="Bus Batteries" where bat_type="Bus";
update application_chat_mapping set  bat_type="Truck Batteries" where bat_type="Trucks";
update application_chat_mapping set  bat_type="Tractor Batteries" where bat_type="Tractors";
update application_chat_mapping set  bat_type="Crane Batteries" where bat_type="Cranes";
update application_chat_mapping set  bat_type="Roller Batteries" where bat_type="Rollers";
update application_chat_mapping set  bat_type="Dozer Batteries" where bat_type="Dozers";
update application_chat_mapping set  bat_type="Excavator Batteries" where bat_type="Excavators";
update application_chat_mapping set  bat_type="Harvestor Batteries" where bat_type="Harvestor";
update application_chat_mapping set  bat_type="Compactor Batteries" where bat_type="Compactors";
update application_chat_mapping set  bat_type="Dumper Batteries" where bat_type="Dumpers";
update application_chat_mapping set  bat_type="Minibus Batteries" where bat_type="Minibus";
update application_chat_mapping set  bat_type="Tyre Handler Batteries" where bat_type="Tyre Handlers";
update application_chat_mapping set  bat_type="Wheeled Harvester Batteries" where bat_type="Wheeled harvester";
update application_chat_mapping set  bat_type="Forwarder Batteries" where bat_type="Forwarders";
update application_chat_mapping set  bat_type="Hydraulic Shovel Batteries" where bat_type="Hydraulic Shovel";
update application_chat_mapping set  bat_type="Construction Equipment Batteries" where bat_type="Construction Equipment";
update application_chat_mapping set  bat_type="Hydralic Excavator Batteries" where bat_type="Hydralic Excavators";
update application_chat_mapping set  bat_type="Loader Batteries" where bat_type="Loaders";
update application_chat_mapping set  bat_type="Telescopic Handler Batteries" where bat_type="Telescopic Handlers";
update application_chat_mapping set  bat_type="Generator Batteries" where bat_type="Generators";
update application_chat_mapping set  bat_type="Genset Batteries" where bat_type="Gensets";
update application_chat_mapping set  bat_type="Special Vehicle Batteries" where bat_type="Special Vehicles";


update battery_order_details set  bat_type="Car Batteries" where bat_type="Four Wheelers";
update battery_order_details set  bat_type="Bike Batteries" where bat_type="Two Wheelers";
update battery_order_details set  bat_type="Inverter Batteries" where bat_type="Inverters";
update battery_order_details set  bat_type="Three Wheeler Batteries" where bat_type="Three Wheelers";
update battery_order_details set  bat_type="Bus Batteries" where bat_type="Bus";
update battery_order_details set  bat_type="Truck Batteries" where bat_type="Trucks";
update battery_order_details set  bat_type="Tractor Batteries" where bat_type="Tractors";
update battery_order_details set  bat_type="Crane Batteries" where bat_type="Cranes";
update battery_order_details set  bat_type="Roller Batteries" where bat_type="Rollers";
update battery_order_details set  bat_type="Dozer Batteries" where bat_type="Dozers";
update battery_order_details set  bat_type="Excavator Batteries" where bat_type="Excavators";
update battery_order_details set  bat_type="Harvestor Batteries" where bat_type="Harvestor";
update battery_order_details set  bat_type="Compactor Batteries" where bat_type="Compactors";
update battery_order_details set  bat_type="Dumper Batteries" where bat_type="Dumpers";
update battery_order_details set  bat_type="Minibus Batteries" where bat_type="Minibus";
update battery_order_details set  bat_type="Tyre Handler Batteries" where bat_type="Tyre Handlers";
update battery_order_details set  bat_type="Wheeled Harvester Batteries" where bat_type="Wheeled harvester";
update battery_order_details set  bat_type="Forwarder Batteries" where bat_type="Forwarders";
update battery_order_details set  bat_type="Hydraulic Shovel Batteries" where bat_type="Hydraulic Shovel";
update battery_order_details set  bat_type="Construction Equipment Batteries" where bat_type="Construction Equipment";
update battery_order_details set  bat_type="Hydralic Excavator Batteries" where bat_type="Hydralic Excavators";
update battery_order_details set  bat_type="Loader Batteries" where bat_type="Loaders";
update battery_order_details set  bat_type="Telescopic Handler Batteries" where bat_type="Telescopic Handlers";
update battery_order_details set  bat_type="Generator Batteries" where bat_type="Generators";
update battery_order_details set  bat_type="Genset Batteries" where bat_type="Gensets";
update battery_order_details set  bat_type="Special Vehicle Batteries" where bat_type="Special Vehicles";

update visitors_orders set  bat_type="Car Batteries" where bat_type="Four Wheelers";
update visitors_orders set  bat_type="Bike Batteries" where bat_type="Two Wheelers";
update visitors_orders set  bat_type="Laptop Batteries" where bat_type="Laptops";
update visitors_orders set  bat_type="Inverter Batteries" where bat_type="Inverters";
update visitors_orders set  bat_type="Three Wheeler Batteries" where bat_type="Three Wheelers";
update visitors_orders set  bat_type="Bus Batteries" where bat_type="Bus";
update visitors_orders set  bat_type="Truck Batteries" where bat_type="Trucks";
update visitors_orders set  bat_type="Tractor Batteries" where bat_type="Tractors";
update visitors_orders set  bat_type="Crane Batteries" where bat_type="Cranes";
update visitors_orders set  bat_type="Roller Batteries" where bat_type="Rollers";
update visitors_orders set  bat_type="Dozer Batteries" where bat_type="Dozers";
update visitors_orders set  bat_type="Excavator Batteries" where bat_type="Excavators";
update visitors_orders set  bat_type="Harvestor Batteries" where bat_type="Harvestor";
update visitors_orders set  bat_type="Compactor Batteries" where bat_type="Compactors";
update visitors_orders set  bat_type="Dumper Batteries" where bat_type="Dumpers";
update visitors_orders set  bat_type="Minibus Batteries" where bat_type="Minibus";
update visitors_orders set  bat_type="Tyre Handler Batteries" where bat_type="Tyre Handlers";
update visitors_orders set  bat_type="Wheeled Harvester Batteries" where bat_type="Wheeled harvester";
update visitors_orders set  bat_type="Forwarder Batteries" where bat_type="Forwarders";
update visitors_orders set  bat_type="Hydraulic Shovel Batteries" where bat_type="Hydraulic Shovel";
update visitors_orders set  bat_type="Construction Equipment Batteries" where bat_type="Construction Equipment";
update visitors_orders set  bat_type="Hydralic Excavator Batteries" where bat_type="Hydralic Excavators";
update visitors_orders set  bat_type="Loader Batteries" where bat_type="Loaders";
update visitors_orders set  bat_type="Telescopic Handler Batteries" where bat_type="Telescopic Handlers";
update visitors_orders set  bat_type="Generator Batteries" where bat_type="Generators";
update visitors_orders set  bat_type="Genset Batteries" where bat_type="Gensets";
update visitors_orders set  bat_type="Special Vehicle Batteries" where bat_type="Special Vehicles";

update battery_health_check set  bat_type="Car Batteries" where bat_type="Four Wheelers";
update battery_health_check set  bat_type="Bike Batteries" where bat_type="Two Wheelers";
update battery_health_check set  bat_type="Inverter Batteries" where bat_type="Inverters";
update battery_health_check set  bat_type="Three Wheeler Batteries" where bat_type="Three Wheelers";
update battery_health_check set  bat_type="Bus Batteries" where bat_type="Bus";
update battery_health_check set  bat_type="Truck Batteries" where bat_type="Trucks";
update battery_health_check set  bat_type="Tractor Batteries" where bat_type="Tractors";
update battery_health_check set  bat_type="Crane Batteries" where bat_type="Cranes";
update battery_health_check set  bat_type="Roller Batteries" where bat_type="Rollers";
update battery_health_check set  bat_type="Dozer Batteries" where bat_type="Dozers";
update battery_health_check set  bat_type="Excavator Batteries" where bat_type="Excavators";
update battery_health_check set  bat_type="Harvestor Batteries" where bat_type="Harvestor";
update battery_health_check set  bat_type="Compactor Batteries" where bat_type="Compactors";
update battery_health_check set  bat_type="Dumper Batteries" where bat_type="Dumpers";
update battery_health_check set  bat_type="Minibus Batteries" where bat_type="Minibus";
update battery_health_check set  bat_type="Tyre Handler Batteries" where bat_type="Tyre Handlers";
update battery_health_check set  bat_type="Wheeled Harvester Batteries" where bat_type="Wheeled harvester";
update battery_health_check set  bat_type="Forwarder Batteries" where bat_type="Forwarders";
update battery_health_check set  bat_type="Hydraulic Shovel Batteries" where bat_type="Hydraulic Shovel";
update battery_health_check set  bat_type="Construction Equipment Batteries" where bat_type="Construction Equipment";
update battery_health_check set  bat_type="Hydralic Excavator Batteries" where bat_type="Hydralic Excavators";
update battery_health_check set  bat_type="Loader Batteries" where bat_type="Loaders";
update battery_health_check set  bat_type="Telescopic Handler Batteries" where bat_type="Telescopic Handlers";
update battery_health_check set  bat_type="Generator Batteries" where bat_type="Generators";
update battery_health_check set  bat_type="Genset Batteries" where bat_type="Gensets";
update battery_health_check set  bat_type="Special Vehicle Batteries" where bat_type="Special Vehicles";


update battery_registration set  bat_type="Car Batteries" where bat_type="Four Wheelers";
update battery_registration set  bat_type="Bike Batteries" where bat_type="Two Wheelers";
update battery_registration set  bat_type="Inverter Batteries" where bat_type="Inverters";
update battery_registration set  bat_type="Three Wheeler Batteries" where bat_type="Three Wheelers";
update battery_registration set  bat_type="Bus Batteries" where bat_type="Bus";
update battery_registration set  bat_type="Truck Batteries" where bat_type="Trucks";
update battery_registration set  bat_type="Tractor Batteries" where bat_type="Tractors";
update battery_registration set  bat_type="Crane Batteries" where bat_type="Cranes";
update battery_registration set  bat_type="Roller Batteries" where bat_type="Rollers";
update battery_registration set  bat_type="Dozer Batteries" where bat_type="Dozers";
update battery_registration set  bat_type="Excavator Batteries" where bat_type="Excavators";
update battery_registration set  bat_type="Harvestor Batteries" where bat_type="Harvestor";
update battery_registration set  bat_type="Compactor Batteries" where bat_type="Compactors";
update battery_registration set  bat_type="Dumper Batteries" where bat_type="Dumpers";
update battery_registration set  bat_type="Minibus Batteries" where bat_type="Minibus";
update battery_registration set  bat_type="Tyre Handler Batteries" where bat_type="Tyre Handlers";
update battery_registration set  bat_type="Wheeled Harvester Batteries" where bat_type="Wheeled harvester";
update battery_registration set  bat_type="Forwarder Batteries" where bat_type="Forwarders";
update battery_registration set  bat_type="Hydraulic Shovel Batteries" where bat_type="Hydraulic Shovel";
update battery_registration set  bat_type="Construction Equipment Batteries" where bat_type="Construction Equipment";
update battery_registration set  bat_type="Hydralic Excavator Batteries" where bat_type="Hydralic Excavators";
update battery_registration set  bat_type="Loader Batteries" where bat_type="Loaders";
update battery_registration set  bat_type="Telescopic Handler Batteries" where bat_type="Telescopic Handlers";
update battery_registration set  bat_type="Generator Batteries" where bat_type="Generators";
update battery_registration set  bat_type="Genset Batteries" where bat_type="Gensets";
update battery_registration set  bat_type="Special Vehicle Batteries" where bat_type="Special Vehicles";


update laptop_details set  battery_type="Laptop Batteries" where battery_type="Laptops";
update laptop_battery_order_details set  battery_type="Laptop Batteries" where battery_type="Laptops";
update laptop_application_chart_mapping set  battery_type="Laptop Batteries" where battery_type="Laptops";